### ISSUE TITLE
Plot annotation capabilities

### ISSUE THREAD

**Issue by lgonzalezsa** [luca-scr/qcc#14]
Greetings,

Thank you for great package in first place.
I would like to know what could be the best practice to do an annotation in a already created qcc plot, where for example I want to make a note over a point (rational or note) and also draw a horizontal line in a desired point. Example below.
Any comment or suggestion welcome.
Luis
![qcc_plot_annotation](https://user-images.githubusercontent.com/704686/51648983-52df8f00-1f48-11e9-9b70-765d1a2461f0.png)

**Comment by luca-scr** [comment]
Have you considered setting `restore.par = FALSE` in the `plot.qcc()` function?

**Comment by lgonzalezsa** [comment]
Thank you for your response and hint for the parameter, now I was able to add my annotation.

Luis
