### ISSUE TITLE
Change or Omit Title on Process Capability Plot

### ISSUE THREAD

**Issue by jrjohnson0821** [luca-scr/qcc#16]
Is there a way to change or omit the title of the plot when using the process.capability function?  I have seen how to do it on others such as the xbar plot, but not this one.  I am trying to write a loop over multiple columns and when I run it, the title always shows the call for the loop df.1[i], rather than the name of the column.

**Comment by luca-scr** [comment]
I added this possibility which was not available before. Please update to the latest version available on GitHub.

**Comment by jrjohnson0821** [comment]
Thank you very much.
