### ISSUE TITLE
qcc : p-chart/np-chart

### ISSUE THREAD

**Issue by nenekis** [luca-scr/qcc#20]
This is what i ran.
m21=qcc(r,type='p',data.name = 'hm',sizes = 9,newdata = rnew)
This is what i got.
Error in qcc(r, type = "p", data.name = "hm", sizes = 9, newdata = rnew) : sample sizes must be given for a p Chart
I found out that i should also provide the 'newsizes' parameter.
I think that 'sample sizes must be given for a p Chart' could be changed to 'new sample sizes must be given for a p Chart'
Maybe this thing is not very important.
Thank you.

**Comment by luca-scr** [comment]
Ok thanks.
