### ISSUE TITLE
Plotting multiple qcc::cusum chart in one display

### ISSUE THREAD

**Issue by MarcoM1007** [luca-scr/qcc#22]
Hi, I am looking for a way to plot more than one cusum chart produced with the cusum() function in one display. I have tried par(mfrow=c(2,1)), layout(), cowplot() and it did not work. In addition, I also tried to convert the cusum plot into a grob so as to use gridExtra::grid.arrange() in advise of other but it still didn't work.

The function mentioned does makes the 1st CUSUM chart smaller and be plotted like normal plot(); successfully plotted 1st CUSUM at top half. However, the 2nd CUSUM chart just refreshes the display automatically instead of being plot below the 1st chart in the same display. Any solution or just possible solution is welcomed, many thanks in advance.

**Comment by luca-scr** [comment]
A minimal working example is always very appreciated. Here is one with the solution to your question:

```
library("qcc")
data(pistonrings)
diameter <- with(pistonrings, qcc.groups(diameter, sample))
q1 <- cusum(diameter[1:25,], decision.interval = 4, se.shift = 1, plot=FALSE)
q2 <- cusum(diameter[1:25,], newdata=diameter[26:40,], plot=FALSE)
par(mfrow = c(1,2))
plot(q1, restore.par = FALSE)
plot(q2, chart.all = FALSE)
```

Note that this works with the current release version on CRAN, but not with the dev version on GitHub.

**Comment by MarcoM1007** [comment]
Thank you very much!!
