### ISSUE TITLE
plots error with single data point

### ISSUE THREAD

**Issue by BrianDiggs** [luca-scr/qcc#26]
## Summary

The plot functions (`plot.qcc`, `plot.ewma.qcc`, `plot.cusum.qcc`, and possibly others, but those were the only ones I checked) throw an error

    Error in plot.window(...) : need finite 'ylim' values

when given a single point of data. The computational part of the functions handle that case well.

## Details

I know a quality control chart with only a single data point does not make any sense and is not really useful. However, when processing batches of data it may occasionally happen. In these cases, it is better for the functions to gracefully handle the edge case rather than fail with an error, possibly bringing down the entire rest of the analysis. In computing the data object (i.e. the `qcc` or `ewma.qcc` class object), a single data point does not create an error and produces an object which represents the data as well as possible; some elements of the object are `NA`, but that is appropriate. However, when this object is plotted, either with `plot = TRUE` in the original call or calling `plot` on the object, an error is thrown.

## Proposed Behavior

I would like to see the plot functions give a best-effort plot when given a single data point.  Not all elements may be present because they might not be defined, but at least it would represent the data and not throw an error.

For example:

```r
ewma(data = 1)
```
![Rplot](https://user-images.githubusercontent.com/463252/94952919-93243e00-049b-11eb-9fc4-9bfd036db830.png)

It's not a great plot, but it is the best possible representation of a EWMA of the data. And it doesn't throw an error.

## Required Changes

Fortunately, almost all the code is robust to this case except for one part. The computation of the y limits fails to give something usable in the single data point case. The fix is easy: just add `na.rm = TRUE` to the range computation.

For example, to get the plot shown above, I just changed [`plot.ewma.qcc` at line 300 in ewma.R](https://github.com/luca-scr/qcc/blob/ac4d293c5026a039393963f267a09f0811f24ee4/R/ewma.R#L300) to

```r
              else range(statistics, limits, na.rm = TRUE),
```

From a quick glance at `plot.qcc` and `plot.cusum.qcc`, it seems an analogous change can be made to the same end, but I have not tried it.

**Comment by luca-scr** [comment]
Thanks, I've included the suggested patch in the dev version on GitHub.
