### ISSUE TITLE
Use the fix for https://github.com/luca-scr/qcc/issues/16 Process.Capability plot name

### ISSUE THREAD

**Issue by da-tucker** [luca-scr/qcc#27]
Thanks so much for this work.  I am using the package with Power BI and attempting to add "title=" or change the dataname.  The version installed with installpackages() is version 2.7.  When I followed the directions for installing the GitHub package, I received the message:

> devtools::install_github("luca-scr/qcc", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo luca-scr/qcc@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/luca-scr/qcc/tarball/master'

**Comment by luca-scr** [comment]
It works for me. I would check if there is any firewall issues.

**Comment by da-tucker** [comment]
Is it possible to get this update into the CRAN?

Thanks, Denise

**Comment by luca-scr** [comment]
It is not ready for CRAN. But it will be someday...
