### ISSUE TITLE
mistake in formula for stdev of p-charts

### ISSUE THREAD

**Issue by erblast** [luca-scr/qcc#29]
Hello thank you for the `qcc` package. It's a great tool for studying statistics for quality control. However, I noticed a mistake in the formula for the standard deviation of p-charts.

```
data(orangejuice)
(q = with(orangejuice, qcc(D[trial], sizes = size[trial], type = "p")))
#> ── Quality Control Chart ───────────────────────── 
#> 
#> Chart type                 = p 
#> Data (phase I)             = D[trial] 
#> Number of groups           = 30 
#> Group sample size          = 50 
#> Center of group statistics = 0.2313333 
#> Standard deviation         = 0.421685 
#> 
#> Control limits at nsigmas  = 3 
#>          LCL       UCL
#>   0.05242755 0.4102391
#>   0.05242755 0.4102391
#> :                     
#>   0.05242755 0.4102391
```

The standard deviation of 0.42 is too high. The correct value should be 0.05963526 So the following test should pass.

```
stopifnot(q$center + 3 * q$std.dev == max(q$limits[,2]))
#> Error: q$center + 3 * q$std.dev == max(q$limits[, 2]) is not TRUE
stopifnot(round(q$center - 3 * q$std.dev, 10) == round(max(q$limits[,1]), 10))
#> Error: round(q$center - 3 * q$std.dev, 10) == round(max(q$limits[, 1]),  .... is not TRUE
```

`sd.np` forgets to include the sample size for calculating the standard deviation.
`limits.np` which produces UCL/LCL calculates stdev correctly.

**Comment by luca-scr** [comment]
Ok, it makes sense. I fixed the bug but not following your commits because I have to take into account possible variable sample sizes.
