### ISSUE TITLE
Question re customisation of rules

### ISSUE THREAD

**Issue by mauriziopassariello** [luca-scr/qcc#35]
Hi,
I have a question re the rules applied for an XmR chart. I need to apply the following:
1. Any point beyond 3sigma
2. A shift of 7 points above or below the centre line
3. A trend of 7 consecutive points all going up or down
4. Any point above or below 3.27 * average moving range

I think the default rules are the WE ones. Is it at all possible to change them? Is there any way I can achieve the 4 rules above with qcc package?

Thanks 

Maurizio

**Comment by luca-scr** [comment]
The implemented rules qcc version 3.* are described in [https://luca-scr.github.io/qcc/reference/rules.html](https://luca-scr.github.io/qcc/reference/rules.html) or in `help(qccRules)`.
There are of course many others rules that could be implemented, but we had to make a decision and, hopefully, we adopted the most used ones. 
Different rules are not automatically available but must be implemented by users using the info returned by `qcc()` function call.
