### ISSUE TITLE
qcc 3.0 - process capability analysis histogram

### ISSUE THREAD

**Issue by mattlitz** [luca-scr/qcc#37]
Started testing qcc 3.0 and am very impressed!  Did find one issue:  the histogram bars in the new process capability analysis chart (using ggplot2) have been extending over the edges of the white plot area (for example: extending over the y-axis).  This occurs in both the R GUI and RStudio.

**Comment by luca-scr** [comment]
Hi, glad you find it useful. Can you provide a minimal reproducible example so I can check and fix what looks like a bug?

**Comment by mattlitz** [comment]
q1 <- qcc(df$amount, 
           type = "xbar.one",
          limits = c(2.5,7.5))
pc <- processCapability(q1, spec.limits = c(3,5))
plot(pc)

![Screenshot 2022-11-06 162837](https://user-images.githubusercontent.com/73509702/200196141-92e75f04-ce20-4985-9a58-cde28f5df40a.png)

**Comment by luca-scr** [comment]
it is not reproducible if `df` is not provided.

**Comment by mattlitz** [comment]
OK I've updated the code!  The overlap appears to occur with small datasets (~50)

**Comment by luca-scr** [comment]
I have uploaded an updated version that should solve the issue.

**Comment by mattlitz** [comment]
Yes that corrected the issue!  Thank you so much!
