### ISSUE TITLE
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0

### ISSUE THREAD

**Issue by duniatri** [luca-scr/qcc#39]
I got below error code when I tried to plot processCapability() output:
```
Warning message:
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
ℹ The deprecated feature was likely used in the qcc package.
  Please report the issue at <https://github.com/luca-scr/qcc/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

the bar of the plot become wide.
![plot](https://github.com/duniatri/pictures/blob/main/Rplot.jpeg?raw=true)

**Comment by duniatri** [comment]
maybe this can help:
https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/

**Comment by duniatri** [comment]
oke, got a solution.
in line 200 of capability.R, edit ..density.. to after_stat(density)
so it will become:
`aes_string(x = "data", y = "after_stat(density)"),`

**Comment by luca-scr** [comment]
Just pushed a fix to this issue. Similar to the one you suggested, but without using `aes_string()`since it is deprecated.
