### ISSUE TITLE
Dot-Dot notation

### ISSUE THREAD

**Issue by mantikera** [luca-scr/qcc#40]
First of all qcc package is awesome and extremely usefull for me..
I noticed that I have the same issue of the friend below @duniatri inform

![erro_qcc_luca](https://user-images.githubusercontent.com/124507788/216824436-b6623031-0409-4d7b-b181-9c455eb08ed3.jpg)

Thanks

**Comment by luca-scr** [comment]
Fixed in the last pushed version of the package.

**Comment by mantikera** [comment]
Ok. Thank you.
