### ISSUE TITLE
Process Capability for non-normal data

### ISSUE THREAD

**Issue by mantikera** [luca-scr/qcc#42]
Hi Luca.
How can I proceed with your package to analyse directly the process capability with non-normal data?
Do I have to "transform" the data before to make the analysis using qcc package?
Some softwares like Minitab have a function/option (Individual Distribution Identification) that gives the information about what kind of distribuition tha non-normal data fits and after that I'm able to make a capability analysis with another distribuition.
Thank you.

**Comment by birdybro** [comment]
https://www.researchgate.net/post/How-could-I-build-a-control-chart-manual-in-R-based-on-non-normal-distribution - possibly relevant information. Here's the link to the white paper for the aglr package that was referenced in their reply:

https://www.researchgate.net/profile/Tomasz-Sobiesciak/post/How-could-I-build-a-control-chart-manual-in-R-based-on-non-normal-distribution/attachment/61925278f5675b211b100899/AS%3A1090384453210113%401636979320611/download/aglr.pdf

And there was a presentation on this years ago:

https://user2011.r-project.org/TalkSlides/Contributed/18Aug_0950_FocusVI_5-ProcessOptimization_2-Roth.pdf

And this paper shows that the assumptions behind each methodological approach should be carefully considered depending on your situation, or else the results are not really useful --> https://core.ac.uk/download/pdf/43632292.pdf

**Comment by mantikera** [comment]
Hi @birdybro . Thank you for the information.
