### ISSUE TITLE
Head start

### ISSUE THREAD

**Issue by PeterBloomfield** [luca-scr/qcc#7]
Hi Luca,

Have you considered adding a head.start argument to cusum()? It looks straightforward to code and document, but I guess it would have to be added to the object so that it could be reported in the summary and on the plot. To avoid squeezing in an extra line at the foot of the plot, it could be reported by adding "(start = ...)" to the "Above target" and "Below target" axis labels (when it's non-zero).

Thoughts?

Peter

**Comment by luca-scr** [comment]
What do you mean by "start"? I don't remember to have seen this type of parameter in a cusum. Of course this is not the same as "center".

**Comment by PeterBloomfield** [comment]
It's a positive value used to initialize the cusum.pos and cusum.neg recursions; described in Montgomery Section 9.1.6 as having been introduced by Lucas and Crosier (1982). It's supported in the ARL calculations in the "spc" package.

**Comment by luca-scr** [comment]
OK, I think is reasonable to add this parameter, which I would call "headstart". 

Looking at the summary.cusum 

decision.interval = 5, se.shift = 1

**Comment by PeterBloomfield** [comment]
Not "head.start", dot-separated like "std.dev", "decision.interval" et al? (I prefer camelCase myself, but dots have a long history in R!)

The chart could be like this:
![screenshot from 2015-10-21 10-12-20](https://cloud.githubusercontent.com/assets/15112970/10639106/6659f62c-77dc-11e5-9105-e397e877da04.png)

Summary.cusum already reports the decision.interval and se.shift parameters, at least in master (I just added one line for "Head start"):

```
> summary(cusum(x, center = 10, std.dev = 1, head = 2.5))

Call:
cusum(data = x, center = 10, std.dev = 1, head.start = 2.5)

cusum chart for x 

Summary of group statistics:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  7.990   9.378  10.440  10.320  11.250  12.290 

Group sample size:  1
Number of groups:  30
Center of group statistics:  10
Standard deviation:  1 

Decision interval (std.err.): 5 
Head start (std.err.): 2.5 
Shift detection  (std. err.): 1 
```

**Comment by luca-scr** [comment]
Ok for "head.start". I do also prefer camelCase now, but 10 years ago that was more or less the standard in R. 
In the summary output Head start is after Decision interval and before Shift detection. Should the latter two parameters be linked together? Why don't we move Head start at the beginning if present?
For the plot, if you set add.stats = FALSE, the information at the bottom is omitted. But then the head.start parameter will appear. Maybe we need to be coherent in the behaviour...

**Comment by PeterBloomfield** [comment]
Head start before Decision interval and Shift detection works for me.

I forgot about add.stats--yes, for consistency, in that case the start could left off the axis label.

Do you want to handle this as a separate pull request?

**Comment by PeterBloomfield** [comment]
BTW, even with add.stats == TRUE I would include information about Head start in the summary and on the chart only if it's non-zero, so neither the summary nor the chart would change when head.start is at the default value of zero.

**Comment by luca-scr** [comment]
Ok it makes sense. Please go ahead with your suggested modifications.

**Comment by PeterBloomfield** [comment]
Thanks for pulling!
